version: "3"
services:
  housing-scraper:
    image: stenterstal/ikzoekeenhuisinenschede-scraper
    container_name: housing-scraper
    restart: unless-stopped
    environment:
      - DEV_MODE=false
      - PRICE_FROM=100
      - PRICE_TO=633
      - CRON_FORMAT=0 6 * * MON,WED,FRI
      - EMAIL=
      - MAILJET_TEMPLATE_ID=
      - MAILJET_API_KEY=
      - MAILJET_SECRET_KEY=
